openapi: 3.1.0
info:
  title: STD24022
  description: This is a specification of STD24022
  version: 1.0.0
servers:
  - url: 'http://localhost:8080'
paths:
  /ping:
    get:
      responses:
        '200':
          description: ok
          content:
            text/plain:
              example: pong

  /cars:
    post:
      responses:
        '201':
          description: created
          content:
            application/json : {
              schema:
                type: object
                example:
                  "id" : 1
                  "brand" : bmw
                  "model": x3
                  "characteristics" : {"max_speed":220, "max_fuel_capacity": 50}
            }

    get:
      responses:
        '200':
          description: ok
          content:
            application/json : {
              schema:
                type: object
                example:
                  "id" : 1
                  "brand" : bmw
                  "model": x3
                  "characteristics" : {"max_speed":220, "max_fuel_capacity": 50}
            }

    get:
      responses:
        '200':
          description: ok
          content:
            application/json : {
              schema:
                required: "id"
                type: object
                example:
                  "id" : 1
                  "brand" : bmw
                  "model": x3
                  "characteristics" : {"max_speed":220, "max_fuel_capacity": 50}
            }
        '404':
          description: not found






  
